server-id: "fe919d5b-4148-414b-861e-9f40ff2699f0"
api-username: prison
api-password: prisonpass1234RV7$e
api-url: "http://localhost:8000/"
default: "default"
currencies:
  default:
    name: "Dollars"
    symbol: "$"
    id: "f0aa6d41-1931-4c3a-8576-4d175779cb51"
    symbol-location: "after"
  tokens:
    name: "Tokens"
    symbol: "Tokens"
    symbol-location: "after"
    id: "81867671-d1c7-4fc5-a266-8f1beacd145a"


#Ignored
starting-balance: 40
allow-negative-balance: false;
