server-id: 1
api-username: prison
api-password: prisonpass1234RV7$e
api-url: "http://104.236.62.75/api/v1"

#Ignored
starting-balance: 40
allow-negative-balance: false;
currencies:
  dollars:
    cache: true
